[package]
name = "compare-packages"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["json", "multipart"] }
rpm = "0.15.1"
serde = { version = "1.0.209", features = ["derive"] }
log = "0.4.22"
tokio = { version = "1.40.0", features = ["macros"] }
